Killaura update
MeteorDevelopment/meteor-client pull request #2031
Opened 2022-02-08 01:05 UTC by N08I40K

2022-02-08 06:20 UTC, idfkingk commented
That's so cool.

2022-02-24 19:40 UTC, SIMULATAN requested changes

2022-02-24 19:40 UTC, SIMULATAN commented on src/main/java/meteordevelopment/meteorclient/systems/modules/combat/KillAura.java
> +    public boolean shieldCheck (PlayerEntity player) { // Minecraft shield checking
I'd remove the space before the brackets to follow the conventions

2022-07-13 15:55 UTC, Yura3313 approved these changes

2022-07-14 14:07 UTC, closed without merging