no gravity entities with correct trajectory and accurate multishot crossbow trajectories
MeteorDevelopment/meteor-client pull request #3818
Opened 2023-07-08 09:36 UTC by xNasuni

## Type of change

- [x] Bug fix
- [ ] New feature

## Description

all the entities with no gravity now have a correct trajectory and multishot crossbows actually show the accurate trajectories of the arrows (10° apart), see screenshots below

## Related issues

i've seen no issues talking about this

# How Has This Been Tested?

insert three screenshots here, 2 comparing with and without no gravity check, and 1 showing multishot

With Gravity
<img src="https://github.com/MeteorDevelopment/meteor-client/assets/62818119/5b0d3a59-3bfd-4838-90f3-82b7b1333ed2" width="400"/>
With No Gravity
<img src="https://github.com/MeteorDevelopment/meteor-client/assets/62818119/1e9bfd50-a5a8-4a55-b246-e88996df9dfa" width="400"/>
Multishot Crossbow
<img src="https://github.com/MeteorDevelopment/meteor-client/assets/62818119/bb79789b-33e9-45a5-a016-ebacbc6ecbcb" width="400"/>

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

2023-07-10 23:02 UTC, MineGame159 requested changes

2023-07-10 23:02 UTC, MineGame159 commented on src/main/java/meteordevelopment/meteorclient/utils/entity/ProjectileEntitySimulator.java
> +            if (noGravity) {
Instead of adding this to every case you can just overwrite the gravity before `return true;` at the end of the method.

2023-07-11 01:47 UTC, xNasuni commented
you're right lol, should be fixed in 2ed8f58 now

2023-07-11 08:45 UTC, MineGame159 commented on src/main/java/meteordevelopment/meteorclient/utils/entity/ProjectileEntitySimulator.java
> +            set(entity, speed, 0, waterDrag, accurate, tickDelta);
You can just do `this.gravity = 0;`

2023-07-11 08:45 UTC, MineGame159 commented on src/main/java/meteordevelopment/meteorclient/utils/entity/ProjectileEntitySimulator.java
> +        this.speed = speed; // so it is known in line 160
What?

2023-07-12 00:14 UTC, xNasuni commented
okay everything actually should be fixed in 693aa62ac9d506c14c0cbddb0fee8f23b793d778
i explained in the commit how i messed up like that 😭

2023-07-12 18:55 UTC, xNasuni commented on src/main/java/meteordevelopment/meteorclient/utils/entity/ProjectileEntitySimulator.java
> -            return false;
how did i mess that up 😭 one second

2023-07-12 18:59 UTC, xNasuni commented
i don't know how but i accidentally overwrote that but there should be no further issue in 4127161d485c0571e56acc3a73c8238d4d19b413 😭

2023-07-12 20:17 UTC, MineGame159 approved these changes

2023-07-12 20:20 UTC, merged