make yaw lock of bounce efly optional and fixed typo
MeteorDevelopment/meteor-client pull request #4035
Opened 2023-09-02 16:40 UTC by Manaball123

## Type of change

- [ ] Bug fix
- [X] New feature

## Description

A summary of the changes along with the reasoning behind the changes.
added option to specify yaw lock for bounce efly

## Related issues

N/A

# How Has This Been Tested?

video in case no believ :D 
https://www.youtube.com/watch?v=PLe9VlmseCE
still uploading tho should be ready in a bit

# Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have added comments to my code in more complex areas.
- [X] I have tested the code in both development and production environments.

2023-09-02 20:15 UTC, RacoonDog commented on src/main/java/meteordevelopment/meteorclient/systems/modules/movement/elytrafly/modes/Bounce.java
> +        throw new IllegalArgumentException("um wtf");
please replace this entire method with
```java
private float getYawDirection() {
    return switch (elytraFly.yawLockMode.get()) {
        case None -> mc.player.getYaw();
        case Smart -> Math.round((mc.player.getYaw() + 1f) / 45f) * 45f;
        case Simple -> elytraFly.yaw.get().floatValue();
    }
}
```

2023-09-02 20:15 UTC, RacoonDog requested changes
womp

2023-09-02 20:17 UTC, GoldenStack commented
womp

2023-09-03 03:33 UTC, Manaball123 commented
^fixed btw

2023-09-06 18:40 UTC, merged