Add a CPS variable to Meteor Starscript
MeteorDevelopment/meteor-client pull request #4057
Opened 2023-09-08 16:44 UTC by panpanpro888

## Type of change

- [ ] Bug fix
- [x] New feature

## Description

Added a CPS variable to the Meteor Starscript that counts the player's clicks per second.

## Related issues

None

# How Has This Been Tested?

As just a Starscript variable, the only form of testing that i can do is open up the game and see if it counts correctly, which it does.

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

2023-09-08 18:20 UTC, Fiz-Victor commented
This can be done by a cps checker thread?

2023-09-08 18:47 UTC, MineGame159 commented
> This can be done by a cps checker thread?

Creating a new thread is absolutely not necessary and wasteful.

And to reply to the original PR. It looks like you forgot to commit some changes since I dont see a way for the `cps` to ever change. Also I have some things to change. It would be best to move this to a separate class, use our static initialization system (look at some other static class) and subscribe to the tick event (possible more events) there. Then there should be a method to get the average CPS instead of doing that manually where the CPS is needed and exposing implementation details. Another thing is that using a list of integer objects is very wasteful since Java doesnt have a proper support for generics, it would be better if you just have a normal int array with the size of 20 (since 20 ticks = one second) and just cycle through it.

2023-09-09 14:34 UTC, panpanpro888 commented
Sorry for the late reply.
I will look into it and do the refactors you said. I will get to working on the commit right now.

2023-09-09 15:15 UTC, panpanpro888 commented
Hi, I am working on it, and while transferring the events from the Minecraft Client Mixin to its own class with event handlers I am having trouble finding an event with the equivalent of the minecraft client's `doAttack` function to listen for when the player clicks. Is it okay to add a function to increment the cps directly into the mixin? Or if there is actually an event for that can you please tell it to me?

2023-09-09 15:18 UTC, MineGame159 commented
There is an `AttackEntityEvent` but that will also count attacks made through modules like Kill Aura. If it shouldnt count those (which in my opinion it shouldnt) then its fine to just directly call the static method from the mixin.

2023-09-09 17:00 UTC, panpanpro888 commented
I can't understand how to make an int array with the size of 20 since the original code had a new array element for every second and then got the average of those elements. Can you please help with this, by the way all the other things are finished.

2023-09-09 22:30 UTC, MineGame159 commented
Ah well I couldnt really make out how the list was supposed to work since a) the `cps` was never incremented and b) the list was never cleared / removed from so it would just fill up your entire memory after a while.
Basically what I meant is that lets say you want the average of the last 5 seconds. Then you would create an array of size 5 and fill it up in circles (0, 1, 2, 3, 4 and then back to 0, etc). This is to not create a billion Integer objects and stress the GC.

2023-09-10 11:08 UTC, panpanpro888 commented
I fixed the previous issues and instead of creating an array of integers, I made it store the total clicks and the seconds the players has been clicking. Already committed and pushed the fixes, code is ready.

2023-09-10 11:09 UTC, Fiz-Victor commented
now cps will be affected by client tick rate?

2023-09-10 11:18 UTC, panpanpro888 commented
The only thing done in the `onTick` event is checking if a second has passed. This was also done in the previous commit but directly from the minecraft client mixin.

2023-09-10 17:08 UTC, MineGame159 requested changes
Otherwise looks good.

2023-09-10 17:08 UTC, MineGame159 commented on src/main/java/meteordevelopment/meteorclient/utils/misc/CPSUtils.java
> +    public static void cpsChecker() {
This doesnt need to be a method, and a public at that. You can just move the body to the `onTick` handler.

2023-09-10 17:08 UTC, MineGame159 commented on src/main/java/meteordevelopment/meteorclient/utils/misc/CPSUtils.java
> +    public static Value getCpsAverage() {
This should return an `int` in case something also wants to get the value.

2023-09-10 17:08 UTC, MineGame159 commented on src/main/java/meteordevelopment/meteorclient/utils/Utils.java
> -
Why. If you want to cleanup then move the 2 constants to the top of the file and with a new line to separate constants and static variables.

2023-09-10 19:27 UTC, MineGame159 approved these changes

2023-09-10 19:30 UTC, merged