Update README.md grammar
MeteorDevelopment/meteor-client pull request #4267
Opened 2023-12-10 17:20 UTC by Yeah-Jack

## Type of change

- [x] Bug fix
- [ ] New feature

## Description

Improve the README grammar.

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

2023-12-10 18:14 UTC, RacoonDog requested changes

2023-12-10 18:14 UTC, RacoonDog commented on README.md
> +Please provide as much information as you can to best help us understand your issue and give us a better chance of it being resolved.
"us" doesn't fit here

2023-12-10 18:14 UTC, RacoonDog commented on README.md
> +You will be rewarded with a role on our Discord server and a customizable in-game cape.  
both "customisable" and "customizable" are valid (and i personally prefer the former)

2023-12-10 18:14 UTC, RacoonDog commented on README.md
> +<p align="center">A Minecraft Fabric Utility Mod for Anarchy Servers </p>
it'd be better to give this proper capitalization instead of starting each word with a capital letter

2023-12-11 17:51 UTC, Yeah-Jack commented on README.md
> +Please provide as much information as you can to best help us understand your issue and give us a better chance of it being resolved.
Why that?

2024-03-25 23:29 UTC, closed without merging