Kotlin Gradle
MeteorDevelopment/meteor-client pull request #4831
Opened 2024-08-16 04:35 UTC by RickyTheRacc

## Type of change

- [ ] Bug fix
- [x] New feature

## Description

Changes the main project and subproject to use the Kotlin Gradle DSL, slightly faster build times and an overall easier to read file

## Related issues

N/A

# How Has This Been Tested?

Worked in both the runClient fabric task as well as the default Minecraft Client configuration by the mcdev plugin, built jar works when tested on a new Prism 1.21.1 instance

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

2024-08-16 12:10 UTC, GreemDev commented
based pr tbh

2024-08-21 00:58 UTC, Lncvrt commented
> slightly faster build times and an overall easier to read file

this is completely pointless lmfao

2024-08-21 14:21 UTC, RickyTheRacc commented
> this is completely pointless lmfao

Small upsides, maybe, but not pointless? The build times are faster, and Kotlin gives more robust errors and is often easier to comprehend for new devs who already started on Java because its syntax is much stricter. If you have any legit concerns though I'm glad to listen ^^

2024-08-21 14:32 UTC, RacoonDog commented
> > slightly faster build times and an overall easier to read file
> 
> this is completely pointless lmfao

anything that removes groovy dsl will never be pointless

2024-08-23 00:37 UTC, RacoonDog requested changes

2024-08-23 00:37 UTC, RacoonDog commented on build.gradle.kts
> +            rename{
add a space (`rename {`) and make into single line, like in the `shadowJar` task

2024-11-05 00:43 UTC, RickyTheRacc commented
Updated all versions and made the thingies oneliners as crobie asked

2024-11-16 01:19 UTC, closed without merging

2024-11-24 20:04 UTC, Lncvrt commented
Why was this canceled?