Add player join/leave messages to Notifier
MeteorDevelopment/meteor-client pull request #4952
Opened 2024-10-14 21:33 UTC by 0xTas

## Type of change

- [ ] Bug fix
- [x] New feature

## Description

This pr adds options to display player join/leave messages in the Notifier module. Includes two different formatting styles, a configurable notification delay, and the option to show only joins, only leaves, neither, or both.

## Related issues

Closes https://github.com/MeteorDevelopment/meteor-client/issues/4929

# How Has This Been Tested?

A screenshot demonstrating both notification styles:
![image](https://github.com/user-attachments/assets/f3fa5901-8c7a-4877-85f1-497c048657dc)

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

2024-10-16 14:30 UTC, Wide-Cat requested changes
Wouldn't it make more sense to send messages based on receiving a PlayerListS2CPacket or PlayerRemoveS2CPacket instead of caching the player list and comparing it between ticks?

2024-10-17 14:57 UTC, 0xTas commented
I suppose it would. How's this?

2024-10-18 20:32 UTC, Wide-Cat approved these changes

2024-10-18 20:34 UTC, merged

2024-10-28 18:34 UTC, nickcat325 commented
Thanks, it works.