Added Left Click Option for Kill Aura
MeteorDevelopment/meteor-client pull request #645
Opened 2021-05-03 21:31 UTC by StormyBytes

Resolves #363

2021-05-03 21:32 UTC, seasnail8169 commented
isn't this what trigger is?

2021-05-03 21:34 UTC, StormyBytes commented
Trigger attacks only when you look at the entity

2021-05-04 16:26 UTC, MobESP commented
What is this point of this?

2021-05-05 02:08 UTC, Declipsonator commented
> What is the point of this?

so that ka only attacks when you want it to

2021-05-05 08:54 UTC, seasnail8169 commented
can we merge trigger and this into KA as one? imo that would make more sense since trigger is literally just ka when looking at someone

2021-05-05 17:29 UTC, ikeafridge4 commented
maybe add this as a setting in trigger

2021-05-05 20:19 UTC, Declipsonator commented
> can we merge trigger and this into KA as one? imo that would make more sense since trigger is literally just ka when looking at someone

Yeh, we could probably just put a only when looking option

2021-05-06 11:47 UTC, seasnail8169 requested changes

2021-05-06 11:47 UTC, seasnail8169 commented on src/main/java/minegame159/meteorclient/systems/modules/combat/KillAura.java
> +            .name("left-click")
Could the naming be consistent please? Maybe "only on click"

2021-05-08 15:37 UTC, merged