Packetfly module
MeteorDevelopment/meteor-client pull request #813
Opened 2021-05-23 01:12 UTC by hashalite

2021-05-23 09:58 UTC, MineGame159 requested changes

2021-05-23 09:58 UTC, MineGame159 commented on src/main/java/minegame159/meteorclient/mixin/EntityMixin.java
> +        if (Modules.get().get(PacketFly.class).isActive()) {info.cancel();}
You should check if the current entity is the player.

2021-05-23 09:58 UTC, MineGame159 commented on src/main/java/minegame159/meteorclient/systems/modules/movement/PacketFly.java
> +    private float pitch;
Can you move the fields below settings and above constructor

2021-05-23 09:58 UTC, MineGame159 commented on src/main/java/minegame159/meteorclient/systems/modules/movement/PacketFly.java
> +        PlayerMoveC2SPacket packet;
I don't see a reason for this field

2021-05-23 09:58 UTC, MineGame159 commented on src/main/java/minegame159/meteorclient/utils/misc/Timer.java
> +public class Timer {
Please name the methods more descriptively, I have no idea what some of them mean.

2021-05-23 09:59 UTC, MineGame159 commented on src/main/java/minegame159/meteorclient/systems/modules/movement/PacketFly.java
> +    private double[] getMotion(double speed) {
Maybe this can be replaced for a method from PlayerUtils class? Not sure but it seems to do similar thing.

2021-05-23 10:13 UTC, MineGame159 requested changes

2021-05-23 10:13 UTC, MineGame159 commented on src/main/java/minegame159/meteorclient/systems/modules/movement/PacketFly.java
> +package minegame159.meteorclient.systems.modules.movement;
License header

2021-05-23 10:13 UTC, MineGame159 commented on src/main/java/minegame159/meteorclient/utils/misc/Timer.java
> +package minegame159.meteorclient.utils.misc;
License header.

2021-05-23 10:15 UTC, MineGame159 commented
Also it might be good to group some of the settings into more groups if its possible.

2021-05-31 00:23 UTC, hashalite commented
Fixed most of what you suggested, I just need to group the settings now.

2021-05-31 03:19 UTC, hashalite commented
Ok, everything should be resolved now

2021-06-02 01:41 UTC, hashalite reviewed
An extra ')' was added after velocity.entityPush.get()

2021-06-14 11:32 UTC, closed without merging